#!/bin/sh
set -e

: "${PORT:=3333}"

if ! [ -d './node_modules' ]; then
  echo 'Installing required NPM modules...'
  npm install
  echo 'Done!'
  echo
fi

if [ "$1" != "-O" ]; then
  ( sleep 2 && open "http://localhost:$PORT/" ) &
fi

set -x; PORT="$PORT" DEV=1 LIVERELOAD=1 exec ./node_modules/.bin/webpack-dev-server \
  --config webpack.config.babel.js \
  --port $PORT \
  --host 0.0.0.0 \
  --output-public-path "/" \
  --colors \
  --hot
