import * as api from '../services/api';
import * as types from './action-types';

// These API methods are available only for logged in users
const authorizedApiMethods = {
  [types.ACCEPT_GROUP_REQUEST]: api.acceptGroupRequest,
  [types.ACCEPT_USER_REQUEST]: api.acceptUserRequest,
  [types.ADD_COMMENT]: api.addComment,
  [types.ARCHIVE_ACTIVITY_REQUEST]: api.archiveRestoreActivity,
  [types.ARCHIVE_RESTORATION_REQUEST]: api.archiveStartRestoration,
  [types.BAN]: api.ban,
  [types.BLOCKED_BY_ME]: api.getBlockedByMe,
  [types.CLOSE_AUTH_SESSIONS]: api.closeAuthSessions,
  [types.CREATE_APP_TOKEN]: api.createAppToken,
  [types.CREATE_FREEFEED_INVITATION]: api.createFreefeedInvitation,
  [types.CREATE_GROUP]: api.createGroup,
  [types.CREATE_HOME_FEED]: api.createHomeFeed,
  [types.CREATE_POST]: api.createPost,
  [types.DEACTIVATE_USER]: api.suspendMe,
  [types.DELETE_APP_TOKEN]: api.deleteAppToken,
  [types.DELETE_COMMENT]: api.deleteComment,
  [types.DELETE_HOME_FEED]: api.deleteHomeFeed,
  [types.DELETE_POST]: api.deletePost,
  [types.DIRECT]: api.getDirect,
  [types.DIRECTS_ALL_READ]: api.markAllDirectsAsRead,
  [types.DISABLE_COMMENTS]: api.disableComments,
  [types.DISCUSSIONS]: api.getDiscussions,
  [types.ENABLE_COMMENTS]: api.enableComments,
  [types.GET_ALL_SUBSCRIPTIONS]: api.getAllSubscriptions,
  [types.GET_APP_TOKENS_SCOPES]: api.getAppTokensScopes,
  [types.GET_APP_TOKENS]: api.getAppTokens,
  [types.GET_AUTH_PROFILES]: api.getExtAuthProfiles,
  [types.GET_NOTIFICATIONS]: api.getNotifications,
  [types.GET_SUMMARY]: api.getSummary,
  [types.HIDE_BY_NAME]: api.hideByName,
  [types.HIDE_POST]: api.hidePost,
  [types.HOME_AUX]: api.getHome,
  [types.HOME]: api.getHome,
  [types.INITIAL_WHO_AM_I]: api.getWhoAmI,
  [types.LIKE_COMMENT]: api.likeComment,
  [types.LIKE_POST]: api.likePost,
  [types.LIST_AUTH_SESSIONS]: api.listAuthSessions,
  [types.LIST_HOME_FEEDS]: api.listHomeFeeds,
  [types.MAKE_GROUP_ADMIN]: api.makeGroupAdmin,
  [types.MEMORIES]: api.getMemories,
  [types.NOTIFICATIONS_ALL_READ]: api.markAllNotificationsAsRead,
  [types.REISSUE_APP_TOKEN]: api.reissueAppToken,
  [types.REISSUE_AUTH_SESSION]: api.reissueAuthSession,
  [types.REJECT_GROUP_REQUEST]: api.rejectGroupRequest,
  [types.REJECT_USER_REQUEST]: api.rejectUserRequest,
  [types.REORDER_HOME_FEEDS]: api.reorderHomeFeeds,
  [types.REVOKE_USER_REQUEST]: api.revokeSentRequest,
  [types.SAVE_EDITING_COMMENT]: api.updateComment,
  [types.SAVE_EDITING_POST]: api.updatePost,
  [types.SAVE_POST]: api.unsavePost,
  [types.SAVES]: api.getSaves,
  [types.SEND_SUBSCRIPTION_REQUEST]: api.subscribeWithHomeFeeds,
  [types.SIGN_OUT]: api.signOut,
  [types.SUBSCRIBE]: api.subscribeWithHomeFeeds,
  [types.SUBSCRIBERS]: api.getSubscribers,
  [types.SUBSCRIPTIONS]: api.getSubscriptions,
  [types.TOGGLE_PINNED_GROUP]: api.togglePinnedGroup,
  [types.UNADMIN_GROUP_ADMIN]: api.unadminGroupAdmin,
  [types.UNBAN]: api.unban,
  [types.UNHIDE_NAMES]: api.unHideNames,
  [types.UNHIDE_POST]: api.unhidePost,
  [types.UNLIKE_COMMENT]: api.unlikeComment,
  [types.UNLIKE_POST]: api.unlikePost,
  [types.UNLINK_EXTERNAL_PROFILE]: api.unlinkExternalProfile,
  [types.UNSUBSCRIBE_FROM_GROUP]: api.unsubscribeFromGroup,
  [types.UNSUBSCRIBE_FROM_ME]: api.unsubscribeFromMe,
  [types.UNSUBSCRIBE]: api.unsubscribe,
  [types.UPDATE_ACTUAL_USER_PREFERENCES]: api.updateActualPreferences,
  [types.UPDATE_APP_TOKEN]: api.updateAppToken,
  [types.UPDATE_GROUP_PICTURE]: api.updateGroupPicture,
  [types.UPDATE_GROUP]: api.updateGroup,
  [types.UPDATE_HOME_FEED]: api.updateHomeFeed,
  [types.UPDATE_PASSWORD]: api.updatePassword,
  [types.UPDATE_SUBSCRIPTION]: api.subscribeWithHomeFeeds,
  [types.UPDATE_USER_NOTIFICATION_PREFERENCES]: api.updateUserPreferences,
  [types.UPDATE_USER_PICTURE]: api.updateUserPicture,
  [types.UPDATE_USER_PREFERENCES]: api.updateUserPreferences,
  [types.UPDATE_USER]: api.updateUser,
  [types.WHO_AM_I]: api.getWhoAmI,
};

// These API methods are available for logged in and anonymous users
const unauthorizedApiMethods = {
  [types.ACTIVATE_USER]: api.resumeMe,
  [types.GET_ALL_GROUPS]: api.getAllGroups,
  [types.GET_BEST_OF]: api.getBestOf,
  [types.GET_COMMENT_LIKES]: api.getCommentLikes,
  [types.GET_EVERYTHING]: api.getEverything,
  [types.GET_INVITATION]: api.getInvitation,
  [types.GET_POST_ID_BY_OLD_NAME]: api.getPostIdByOldName,
  [types.GET_SEARCH]: api.getSearch,
  [types.GET_SERVER_INFO]: api.getServerInfo,
  [types.GET_SINGLE_POST]: api.getPost,
  [types.GET_USER_COMMENTS]: api.getUserComments,
  [types.GET_USER_FEED]: api.getUserFeed,
  [types.GET_USER_INFO]: api.getUserInfo,
  [types.GET_USER_LIKES]: api.getUserLikes,
  [types.GET_USER_MEMORIES]: api.getUserMemories,
  [types.GET_USER_SUMMARY]: api.getUserSummary,
  [types.RESET_PASSWORD]: api.resetPassword,
  [types.RESTORE_PASSWORD]: api.restorePassword,
  [types.SHOW_MORE_COMMENTS]: api.getPost,
  [types.SHOW_MORE_LIKES_ASYNC]: api.getLikesOnly,
  [types.SIGN_IN]: api.signIn,
  [types.SIGN_UP]: api.signUp,
};

export const apiMapping = { ...authorizedApiMethods, ...unauthorizedApiMethods };

export function requiresAuth(actionType) {
  return !!authorizedApiMethods[actionType];
}
